# Form implementation generated from reading ui file 'admin_login.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Admin_Login(object):
    def setupUi(self, Admin_Login):
        Admin_Login.setObjectName("Admin_Login")
        Admin_Login.resize(404, 204)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/profile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Admin_Login.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Admin_Login)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 201))
        self.frame.setStyleSheet("QFrame{border-radius:23px;background-color:rgb(30, 30, 30)}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 10, 60, 60))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/profile.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_2.setStyleSheet("color:white\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnexit = QtWidgets.QPushButton(self.frame)
        self.btnexit.setGeometry(QtCore.QRect(380, -1, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setBold(True)
        font.setWeight(75)
        self.btnexit.setFont(font)
        self.btnexit.setStyleSheet("background-color:rgbrgb(218, 218, 218);color:black")
        self.btnexit.setObjectName("btnexit")
        self.btnminimize = QtWidgets.QPushButton(self.frame)
        self.btnminimize.setGeometry(QtCore.QRect(362, -1, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnminimize.setFont(font)
        self.btnminimize.setStyleSheet("background-color:rgbrgb(218, 218, 218);color:black")
        self.btnminimize.setObjectName("btnminimize")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(30, 100, 341, 80))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:white\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.usernameinput = QtWidgets.QLineEdit(self.groupBox)
        self.usernameinput.setGeometry(QtCore.QRect(65, 20, 211, 22))
        self.usernameinput.setStyleSheet("background-color:white;color:black")
        self.usernameinput.setObjectName("usernameinput")
        self.passwordinput = QtWidgets.QLineEdit(self.groupBox)
        self.passwordinput.setGeometry(QtCore.QRect(65, 48, 211, 22))
        self.passwordinput.setStyleSheet("background-color:white;color:black")
        self.passwordinput.setObjectName("passwordinput")
        self.btnlogin = QtWidgets.QPushButton(self.groupBox)
        self.btnlogin.setGeometry(QtCore.QRect(280, 49, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.btnlogin.setFont(font)
        self.btnlogin.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.btnlogin.setObjectName("btnlogin")

        Admin_Login.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Admin_Login.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.btnexit.clicked.connect(lambda: Admin_Login.close())
        self.btnminimize.clicked.connect(lambda: Admin_Login.showMinimized())
        self.passwordinput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.btnlogin.clicked.connect(self.checkAccount)

        self.retranslateUi(Admin_Login)
        QtCore.QMetaObject.connectSlotsByName(Admin_Login)


    def checkAccount(self):
        if len(self.usernameinput.text()) != 0 and len(self.passwordinput.text()) != 0:
            username = 'adminid'
            password = 'adminpw'
            if self.usernameinput.text() == username and self.passwordinput.text() == password:
                from Homepage import Ui_MainWindow
                self.home = QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow()
                self.ui.setupUi(self.home)
                self.home.show()
            else:
                from PyQt6.QtWidgets import QMessageBox
                self.log = QMessageBox()
                self.log.setWindowTitle('Employee Management System')
                self.log.setWindowIcon(QtGui.QIcon('profile.png'))
                self.log.setIcon(QMessageBox.Icon.Warning)
                self.log.setText('Incorrect username/password.')
                self.log.show()


    def retranslateUi(self, Admin_Login):
        _translate = QtCore.QCoreApplication.translate
        Admin_Login.setWindowTitle(_translate("Admin_Login", "Employee Management System - Admin Login"))
        self.label_2.setText(_translate("Admin_Login", "Employee Management System"))
        self.btnexit.setText(_translate("Admin_Login", "x"))
        self.btnminimize.setText(_translate("Admin_Login", "-"))
        self.groupBox.setTitle(_translate("Admin_Login", "Admin Login"))
        self.usernameinput.setPlaceholderText(_translate("Admin_Login", " Username"))
        self.passwordinput.setPlaceholderText(_translate("Admin_Login", " Password"))
        self.btnlogin.setText(_translate("Admin_Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_Login = QtWidgets.QWidget()
    ui = Ui_Admin_Login()
    ui.setupUi(Admin_Login)
    Admin_Login.show()
    sys.exit(app.exec())
