# Form implementation generated from reading ui file 'employee_login.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Employee_Login(object):
    def setupUi(self, Employee_Login):
        Employee_Login.setObjectName("Employee_Login")
        Employee_Login.resize(404, 204)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/profile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Employee_Login.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Employee_Login)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 201))
        self.frame.setStyleSheet("QFrame{border-radius:23px;background-color:rgb(30, 30, 30)}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 10, 60, 60))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/profile.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_2.setStyleSheet("color:white\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnexit = QtWidgets.QPushButton(self.frame)
        self.btnexit.setGeometry(QtCore.QRect(380, -1, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setBold(True)
        font.setWeight(75)
        self.btnexit.setFont(font)
        self.btnexit.setStyleSheet("background-color:rgbrgb(218, 218, 218);color:black")
        self.btnexit.setObjectName("btnexit")
        self.btnminimize = QtWidgets.QPushButton(self.frame)
        self.btnminimize.setGeometry(QtCore.QRect(362, -1, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnminimize.setFont(font)
        self.btnminimize.setStyleSheet("background-color:rgbrgb(218, 218, 218);color:black")
        self.btnminimize.setObjectName("btnminimize")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(30, 100, 341, 80))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:white\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.usernameinput = QtWidgets.QLineEdit(self.groupBox)
        self.usernameinput.setGeometry(QtCore.QRect(65, 20, 211, 22))
        self.usernameinput.setStyleSheet("background-color:white;color:black")
        self.usernameinput.setObjectName("usernameinput")
        self.passwordinput = QtWidgets.QLineEdit(self.groupBox)
        self.passwordinput.setGeometry(QtCore.QRect(65, 48, 211, 22))
        self.passwordinput.setStyleSheet("background-color:white;color:black")
        self.passwordinput.setObjectName("passwordinput")
        self.btnlogin = QtWidgets.QPushButton(self.groupBox)
        self.btnlogin.setGeometry(QtCore.QRect(280, 49, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.btnlogin.setFont(font)
        self.btnlogin.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.btnlogin.setObjectName("btnlogin")

        Employee_Login.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Employee_Login.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.btnexit.clicked.connect(lambda: Employee_Login.close())
        self.btnminimize.clicked.connect(lambda: Employee_Login.showMinimized())
        self.btnlogin.clicked.connect(self.checkAccount)
        self.passwordinput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.retranslateUi(Employee_Login)
        QtCore.QMetaObject.connectSlotsByName(Employee_Login)

    def retranslateUi(self, Employee_Login):
        _translate = QtCore.QCoreApplication.translate
        Employee_Login.setWindowTitle(_translate("Employee_Login", "Employee Management System - Employee Attendance Login"))
        self.label_2.setText(_translate("Employee_Login", "Employee Management System"))
        self.btnexit.setText(_translate("Employee_Login", "x"))
        self.btnminimize.setText(_translate("Employee_Login", "-"))
        self.groupBox.setTitle(_translate("Employee_Login", "Employee Attendance Login"))
        self.usernameinput.setPlaceholderText(_translate("Employee_Login", " Username"))
        self.passwordinput.setPlaceholderText(_translate("Employee_Login", " Password"))
        self.btnlogin.setText(_translate("Employee_Login", "Login"))

    def checkAccount(self):
        if len(self.usernameinput.text()) != 0 and len(self.passwordinput.text()) != 0:
   
                import mysql.connector
                db = mysql.connector.connect(
                    host = 'localhost',
                    user = 'root',
                    password = 'root',
                    database = 'emp_management_db'
                )
                cursor = db.cursor()
                cursor.execute(f'select * from emp_account where EmpUsername = "{self.usernameinput.text()}"')
                accounts = cursor.fetchall()

                validation = 0

                for account in accounts:
                    self.employeeName = account[0]
                    validation += 1
                    if account[2] == self.passwordinput.text():
                        self.acceptAttendance()
                    else:
                        from PyQt6.QtWidgets import QMessageBox
                        self.log = QMessageBox()
                        self.log.setWindowTitle('Employee Management System')
                        self.log.setWindowIcon(QtGui.QIcon('profile.png'))
                        self.log.setIcon(QMessageBox.Icon.Warning)
                        self.log.setText('Incorrect username/password.')
                        self.log.show()
                if validation == 0:
                    from PyQt6.QtWidgets import QMessageBox
                    self.log = QMessageBox()
                    self.log.setWindowTitle('Employee Management System')
                    self.log.setWindowIcon(QtGui.QIcon('profile.png'))
                    self.log.setIcon(QMessageBox.Icon.Warning)
                    self.log.setText('No Employee found.')
                    self.log.show()

    
    def acceptAttendance(self):
        from datetime import datetime
        from PyQt6.QtWidgets import QMessageBox
        import mysql.connector
        
        db = mysql.connector.connect(
            host = 'localhost',
            user = 'root',
            password = 'root',
            database = 'emp_management_db'
        )
        cursor = db.cursor()

        dt = datetime.now()
        DateTime = dt.strftime('%B %d, %Y - %I:%M%p ')
        cursor.execute(f'insert into emp_attendance values("{self.employeeName}","{DateTime}")')
        db.commit()
        
        self.log = QMessageBox()
        self.log.setWindowTitle('Employee Management System')
        self.log.setWindowIcon(QtGui.QIcon('profile.png'))
        self.log.setIcon(QMessageBox.Icon.Information)
        self.log.setText('Welcome, you are now logged in.')
        self.log.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Employee_Login = QtWidgets.QWidget()
    ui = Ui_Employee_Login()
    ui.setupUi(Employee_Login)
    Employee_Login.show()
    sys.exit(app.exec())
