# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FirstWindow(object):
    def setupUi(self, FirstWindow):
        FirstWindow.setObjectName("FirstWindow")
        FirstWindow.resize(420, 219)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/profile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FirstWindow.setWindowIcon(icon)
        FirstWindow.setStyleSheet("background-color:rgb(30, 30, 30)")
        self.frame = QtWidgets.QFrame(FirstWindow)
        self.frame.setGeometry(QtCore.QRect(10, 10, 401, 201))
        self.frame.setStyleSheet("QFrame{border-radius:23px;background-color:rgb(30, 30, 30)}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 10, 60, 60))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/profile.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_2.setStyleSheet("color:white\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnexit = QtWidgets.QPushButton(self.frame)
        self.btnexit.setGeometry(QtCore.QRect(380, -1, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setBold(True)
        font.setWeight(75)
        self.btnexit.setFont(font)
        self.btnexit.setStyleSheet("background-color:rgbrgb(218, 218, 218);color:black")
        self.btnexit.setObjectName("btnexit")
        self.btnminimize = QtWidgets.QPushButton(self.frame)
        self.btnminimize.setGeometry(QtCore.QRect(362, -1, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnminimize.setFont(font)
        self.btnminimize.setStyleSheet("background-color:rgbrgb(218, 218, 218);color:black")
        self.btnminimize.setObjectName("btnminimize")
        self.btnemployeelogin = QtWidgets.QPushButton(self.frame)
        self.btnemployeelogin.setGeometry(QtCore.QRect(110, 150, 182, 28))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setBold(False)
        font.setWeight(50)
        self.btnemployeelogin.setFont(font)
        self.btnemployeelogin.setStyleSheet("background-color:rgb(255, 0, 0);color:white")
        self.btnemployeelogin.setObjectName("btnemployeelogin")
        self.btnadminlogin = QtWidgets.QPushButton(self.frame)
        self.btnadminlogin.setGeometry(QtCore.QRect(110, 120, 182, 28))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setBold(False)
        font.setWeight(50)
        self.btnadminlogin.setFont(font)
        self.btnadminlogin.setStyleSheet("background-color:rgb(255, 0, 0);color:white")
        self.btnadminlogin.setObjectName("btnadminlogin")


        FirstWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        FirstWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.btnexit.clicked.connect(lambda: FirstWindow.close())
        self.btnminimize.clicked.connect(lambda: FirstWindow.showMinimized())
        self.btnadminlogin.clicked.connect(self.AdminLogin)
        self.btnemployeelogin.clicked.connect(self.EmployeeLogin)
        self.CreateDatabaseTables()

        self.retranslateUi(FirstWindow)
        QtCore.QMetaObject.connectSlotsByName(FirstWindow)
    
    def AdminLogin(self):
        from admin_loginpage import Ui_Admin_Login
        self.admin = QtWidgets.QWidget()
        self.ui = Ui_Admin_Login()
        self.ui.setupUi(self.admin)
        self.admin.show()

    def EmployeeLogin(self):
        from employee_loginpage import Ui_Employee_Login
        self.employee = QtWidgets.QWidget()
        self.ui = Ui_Employee_Login()
        self.ui.setupUi(self.employee)
        self.employee.show()

    def CreateDatabaseTables(self):
        import mysql.connector

        db = mysql.connector.connect(
            host = 'localhost',
            user = 'root',
            password = 'root'
        )
        cursor = db.cursor()
        cursor.execute('create database if not exists emp_management_db')

        db = mysql.connector.connect(
            host = 'localhost',
            user = 'root',
            password = 'root',
            database = 'emp_management_db'
        )
        cursor = db.cursor()

        cursor.execute('''create table if not exists emp_info_tb
        (
            EmpName varchar(256) primary key not null,
            EmpContact varchar(256) not null,
            EmpEmail varchar(256) not null,
            EmpGender varchar(256) not null,
            EmpAge int not null,
            EmpBirthdate varchar(256) not null,
            EmpAddress varchar(256) not null,
            EmpSalary varchar(256)
        )
        ''')

        cursor.execute('''create table if not exists emp_account
        (
            EmpName varchar(256) primary key not null,
            EmpUsername varchar(256) not null,
            EmpPassword varchar(256) not null
        )
        ''')

        cursor.execute('''create table if not exists emp_attendance
        (
            EmpName varchar(256) not null,
            Attendance varchar(256)
        )
        ''')  

    def retranslateUi(self, FirstWindow):
        _translate = QtCore.QCoreApplication.translate
        FirstWindow.setWindowTitle(_translate("FirstWindow", " "))
        self.label_2.setText(_translate("FirstWindow", "Employee Management System"))
        self.btnexit.setText(_translate("FirstWindow", "x"))
        self.btnminimize.setText(_translate("FirstWindow", "-"))
        self.btnemployeelogin.setText(_translate("FirstWindow", "Employee Attendance"))
        self.btnadminlogin.setText(_translate("FirstWindow", "Admin Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FirstWindow = QtWidgets.QWidget()
    ui = Ui_FirstWindow()
    ui.setupUi(FirstWindow)
    FirstWindow.show()
    sys.exit(app.exec())
