
from PyQt6 import QtCore, QtGui, QtWidgets
from MainWindow import Ui_MainWindow

class Ui_LoginAdmin(object):
    def setupUi(self, AdminLogin):
        AdminLogin.setObjectName("AdminLogin")
        AdminLogin.resize(537, 271)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ccmslogo.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AdminLogin.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(AdminLogin)
        self.frame.setGeometry(QtCore.QRect(270, 0, 271, 271))
        self.frame.setStyleSheet("background-color:rgb(34, 54, 90)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 251, 231))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border:1px solid white;color:white;")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.LineEditPassword_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LineEditPassword_2.setGeometry(QtCore.QRect(40, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LineEditPassword_2.setFont(font)
        self.LineEditPassword_2.setStyleSheet("background-color:white;color:black;border:1px solid black")
        self.LineEditPassword_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LineEditPassword_2.setPlaceholderText(" Password")
        self.LineEditPassword_2.setObjectName("LineEditPassword_2")
        self.LineEditUsername_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LineEditUsername_2.setGeometry(QtCore.QRect(40, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LineEditUsername_2.setFont(font)
        self.LineEditUsername_2.setStyleSheet("background-color:white;color:black;border:1px solid black")
        self.LineEditUsername_2.setObjectName("LineEditUsername_2")
        self.ButtonLogin_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonLogin_2.setGeometry(QtCore.QRect(150, 140, 71, 22))
        self.ButtonLogin_2.setStyleSheet("background-color:rgb(177, 177, 177);color:black")
        self.ButtonLogin_2.setIconSize(QtCore.QSize(15, 15))
        self.ButtonLogin_2.setObjectName("ButtonLogin_2")
        self.frame_4 = QtWidgets.QFrame(AdminLogin)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 271, 271))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("QFrame{background-color:rgb(243, 243, 243);}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 241, 81))
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(25, 39, 65);border:none")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 121, 121))
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border:none")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/ccmslogo.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(270, 0, 271, 271))
        self.frame_6.setStyleSheet("background-color:rgb(34, 54, 90)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 251, 231))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("border:1px solid white;color:white;")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.groupBox_4.setObjectName("groupBox_4")
        self.LineEditPassword_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.LineEditPassword_4.setGeometry(QtCore.QRect(40, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LineEditPassword_4.setFont(font)
        self.LineEditPassword_4.setStyleSheet("background-color:white;color:black;border:1px solid black")
        self.LineEditPassword_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LineEditPassword_4.setPlaceholderText(" Password")
        self.LineEditPassword_4.setObjectName("LineEditPassword_4")
        self.LineEditUsername_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.LineEditUsername_4.setGeometry(QtCore.QRect(40, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LineEditUsername_4.setFont(font)
        self.LineEditUsername_4.setStyleSheet("background-color:white;color:black;border:1px solid black")
        self.LineEditUsername_4.setObjectName("LineEditUsername_4")
        self.ButtonLogin_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.ButtonLogin_4.setGeometry(QtCore.QRect(150, 140, 71, 22))
        self.ButtonLogin_4.setStyleSheet("background-color:rgb(177, 177, 177);color:black")
        self.ButtonLogin_4.setIconSize(QtCore.QSize(15, 15))
        self.ButtonLogin_4.setObjectName("ButtonLogin_4")
        AdminLogin.setTabOrder(self.LineEditUsername_2,self.LineEditPassword_2)

        self.ButtonLogin_2.clicked.connect(self.checkAdminAccount)


        self.retranslateUi(AdminLogin)
        QtCore.QMetaObject.connectSlotsByName(AdminLogin)

    def checkAdminAccount(self): 
        CorrectUsername = 'admin'
        CorrectPassword = '1234'

        CurrentUsername = self.LineEditUsername_2.text()
        CurrentPassword = self.LineEditPassword_2.text() 

        if len(CurrentUsername) != 0 and len(CurrentPassword) != 0:
            if CurrentUsername == CorrectUsername and CurrentPassword == CorrectPassword:
                        self.window = QtWidgets.QMainWindow()
                        self.ui = Ui_MainWindow()
                        self.ui.setupUi(self.window)
                        self.window.show()
            else:
                from PyQt6.QtWidgets import QMessageBox
                self.mbox = QMessageBox()
                self.mbox.setWindowIcon(QtGui.QIcon("images/ccmslogo.jpg"))
                self.mbox.setIcon(QMessageBox.Icon.Warning)
                self.mbox.setWindowTitle(' ')
                self.mbox.setText('Incorrect username / password.')
                self.mbox.setStandardButtons(QMessageBox.StandardButton.Ok)
                self.mbox.show()


    def retranslateUi(self, AdminLogin):
        _translate = QtCore.QCoreApplication.translate
        AdminLogin.setWindowIcon(QtGui.QIcon('images/ccmslogo.jpg'))
        AdminLogin.setWindowTitle(_translate("AdminLogin", "CCSM Student Information System | Admin Login"))
        self.groupBox_2.setTitle(_translate("AdminLogin", "ADMIN LOGIN"))
        self.LineEditUsername_2.setPlaceholderText(_translate("AdminLogin", " Username"))
        self.ButtonLogin_2.setText(_translate("AdminLogin", "Login"))
        self.label_5.setText(_translate("AdminLogin", "CCMS Student\n"
"Information System"))
        self.groupBox_4.setTitle(_translate("AdminLogin", "ADMIN LOGIN"))
        self.LineEditUsername_4.setPlaceholderText(_translate("AdminLogin", " Username"))
        self.ButtonLogin_4.setText(_translate("AdminLogin", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminLogin = QtWidgets.QWidget()
    ui = Ui_LoginAdmin()
    ui.setupUi(AdminLogin)
    AdminLogin.show()
    sys.exit(app.exec())
