from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_Transactions(object):
    def setupUi(self, Transactions):
        Transactions.setObjectName("Transactions")
        Transactions.resize(738, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/credit-card.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Transactions.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Transactions)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 741, 511))
        self.frame_2.setStyleSheet("background-color:rgb(7, 44, 112)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(20, 20, 701, 471))
        self.frame.setStyleSheet("QFrame{background-color:rgb(11, 58, 151);border: 3px solid rgb(7, 44, 112)}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btn_Minimize = QtWidgets.QPushButton(self.frame)
        self.btn_Minimize.setGeometry(QtCore.QRect(620, 0, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Minimize.setFont(font)
        self.btn_Minimize.setStyleSheet("background:none;border-radius: 16px;color:white")
        self.btn_Minimize.setFlat(True)
        self.btn_Minimize.setObjectName("btn_Minimize")
        self.btn_Exit = QtWidgets.QPushButton(self.frame)
        self.btn_Exit.setGeometry(QtCore.QRect(660, 0, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Exit.setFont(font)
        self.btn_Exit.setStyleSheet("background:none;border-radius: 16px;color:white")
        self.btn_Exit.setFlat(True)
        self.btn_Exit.setObjectName("btn_Exit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 20, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;color:white")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(250, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;color:white")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images/credit-card.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_ID = QtWidgets.QLabel(self.frame)
        self.label_ID.setGeometry(QtCore.QRect(20, 290, 55, 16))
        self.label_ID.setStyleSheet("background-color:rgb(11, 58, 151);color::rgb(11, 58, 151);border:none;")
        self.label_ID.setText("")
        self.label_ID.setObjectName("label_ID")
        self.btn_DeleteAllTransactions = QtWidgets.QPushButton(self.frame)
        self.btn_DeleteAllTransactions.setGeometry(QtCore.QRect(260, 430, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.btn_DeleteAllTransactions.setFont(font)
        self.btn_DeleteAllTransactions.setStyleSheet("background-color:rgb(44, 48, 61);color:white")
        self.btn_DeleteAllTransactions.setObjectName("btn_DeleteAllTransactions")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(170, 80, 361, 341))
        self.tableWidget.setStyleSheet("border:2px solid black;background-color:white;color:black;padding:2px")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        Transactions.setCentralWidget(self.centralwidget)
        Transactions.setCentralWidget(self.centralwidget)
        Transactions.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Transactions.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.btn_Exit.clicked.connect(Transactions.close)
        self.btn_Minimize.clicked.connect(Transactions.showMinimized)
        self.tableWidget.horizontalHeader().hide()
        self.tableWidget.verticalHeader().hide()
        self.btn_DeleteAllTransactions.setEnabled(False)
        self.btn_DeleteAllTransactions.clicked.connect(self.DeleteValidation)

        from ATM_DashboardWindow import Ui_Dashboard
        self.dashboard = QtWidgets.QMainWindow()
        self.ui = Ui_Dashboard()
        self.ui.setupUi(self.dashboard)
        self.dashboard.close()

        self.retranslateUi(Transactions)
        QtCore.QMetaObject.connectSlotsByName(Transactions)

    def DeleteValidation(self):
        from PyQt6.QtWidgets import QMessageBox
        self.deleteall = QMessageBox()
        self.deleteall.setWindowIcon(QtGui.QIcon('images/credit-card.png'))
        self.deleteall.setWindowTitle('HS ATM')
        self.deleteall.setIcon(QMessageBox.Icon.NoIcon)
        self.deleteall.setText('Are you sure you to want to continue?')
        self.deleteall.setInformativeText('This action cannot be undone.')
        self.deleteall.setStandardButtons(QMessageBox.StandardButton.Yes|QMessageBox.StandardButton.Cancel)
        self.deleteall.buttonClicked.connect(self.DeleteTransactions)
        self.deleteall.show()

    def DeleteTransactions(self,a):
        if a.text() == '&Yes':
            DATABASE = mysql.connector.connect(host='localhost', user='root',password='root',database='ATM_DB')
            CURSOR = DATABASE.cursor()
            CURSOR.execute(f'DELETE FROM account_transactions')
            DATABASE.commit()
            self.tableWidget.clear()

    def retranslateUi(self, Transactions):
        _translate = QtCore.QCoreApplication.translate
        Transactions.setWindowTitle(_translate("Transactions", "HS ATM Transaction History"))
        self.btn_Minimize.setText(_translate("Transactions", "-"))
        self.btn_Exit.setText(_translate("Transactions", "x"))
        self.label.setText(_translate("Transactions", "HS ATM"))
        self.btn_DeleteAllTransactions.setText(_translate("Transactions", "Delete All Transactions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Transactions = QtWidgets.QMainWindow()
    ui = Ui_Transactions()
    ui.setupUi(Transactions)
    Transactions.show()
    sys.exit(app.exec())
