from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(738, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/credit-card.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dashboard.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 741, 511))
        self.frame_2.setStyleSheet("background-color:rgb(7, 44, 112)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(20, 20, 701, 471))
        self.frame.setStyleSheet("QFrame{background-color:rgb(11, 58, 151);border: 3px solid rgb(7, 44, 112)}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btn_Minimize = QtWidgets.QPushButton(self.frame)
        self.btn_Minimize.setGeometry(QtCore.QRect(620, 0, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Minimize.setFont(font)
        self.btn_Minimize.setStyleSheet("background:none;border-radius: 16px;color:white")
        self.btn_Minimize.setFlat(True)
        self.btn_Minimize.setObjectName("btn_Minimize")
        self.btn_Exit = QtWidgets.QPushButton(self.frame)
        self.btn_Exit.setGeometry(QtCore.QRect(660, 0, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Exit.setFont(font)
        self.btn_Exit.setStyleSheet("background:none;border-radius: 16px;color:white")
        self.btn_Exit.setFlat(True)
        self.btn_Exit.setObjectName("btn_Exit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;color:rgb(0, 162, 255)")
        self.label_2.setObjectName("label_2")
        self.label_User = QtWidgets.QLabel(self.frame)
        self.label_User.setGeometry(QtCore.QRect(20, 140, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_User.setFont(font)
        self.label_User.setStyleSheet("border:none;color:white")
        self.label_User.setObjectName("label_User")
        self.label_Balance = QtWidgets.QLabel(self.frame)
        self.label_Balance.setGeometry(QtCore.QRect(40, 210, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_Balance.setFont(font)
        self.label_Balance.setStyleSheet("border:none;color:white")
        self.label_Balance.setObjectName("label_Balance")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:none;color:rgb(0, 162, 255)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border:none;color:white")
        self.label_6.setObjectName("label_6")
        self.btn_GetCash = QtWidgets.QPushButton(self.frame)
        self.btn_GetCash.setGeometry(QtCore.QRect(300, 120, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btn_GetCash.setFont(font)
        self.btn_GetCash.setStyleSheet("background-color:rgb(1, 180, 245);color:white")
        self.btn_GetCash.setObjectName("btn_GetCash")
        self.btn_Deposit = QtWidgets.QPushButton(self.frame)
        self.btn_Deposit.setGeometry(QtCore.QRect(500, 120, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btn_Deposit.setFont(font)
        self.btn_Deposit.setStyleSheet("background-color:rgb(1, 180, 245);color:white")
        self.btn_Deposit.setObjectName("btn_Deposit")
        self.btn_AccountSettings = QtWidgets.QPushButton(self.frame)
        self.btn_AccountSettings.setGeometry(QtCore.QRect(300, 190, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btn_AccountSettings.setFont(font)
        self.btn_AccountSettings.setStyleSheet("background-color:rgb(1, 180, 245);color:white")
        self.btn_AccountSettings.setObjectName("btn_AccountSettings")
        self.btn_TransactionHistory = QtWidgets.QPushButton(self.frame)
        self.btn_TransactionHistory.setGeometry(QtCore.QRect(500, 190, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btn_TransactionHistory.setFont(font)
        self.btn_TransactionHistory.setStyleSheet("background-color:rgb(1, 180, 245);color:white")
        self.btn_TransactionHistory.setObjectName("btn_TransactionHistory")
        self.btn_About = QtWidgets.QPushButton(self.frame)
        self.btn_About.setGeometry(QtCore.QRect(20, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.btn_About.setFont(font)
        self.btn_About.setStyleSheet("background:rgb(11, 58, 151);color:rgb(0, 136, 255)")
        self.btn_About.setFlat(True)
        self.btn_About.setObjectName("btn_About")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;color:white")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images/credit-card.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_ID = QtWidgets.QLabel(self.frame)
        self.label_ID.setGeometry(QtCore.QRect(20, 290, 55, 16))
        self.label_ID.setStyleSheet("background-color:rgb(11, 58, 151);color:rgb(11, 58, 151);border:none;")
        self.label_ID.setText("")
        self.label_ID.setObjectName("label_ID")
        Dashboard.setCentralWidget(self.centralwidget)
        Dashboard.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Dashboard.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.btn_Exit.clicked.connect(Dashboard.close)
        self.btn_Minimize.clicked.connect(Dashboard.showMinimized)
        self.btn_About.clicked.connect(self.AboutTheBank)
        self.btn_AccountSettings.clicked.connect(self.ShowAccountSettings)
        self.btn_Deposit.clicked.connect(self.ShowDepositWindow)
        self.btn_GetCash.clicked.connect(self.ShowWithdrawWindow)

        self.btn_Exit.clicked.connect(self.ShowLogin)
        self.btn_AccountSettings.clicked.connect(lambda:Dashboard.close())
        self.btn_Deposit.clicked.connect(lambda:Dashboard.close())
        self.btn_GetCash.clicked.connect(lambda:Dashboard.close())
        self.btn_TransactionHistory.clicked.connect(self.ShowTransactions)

        from ATM_LoginWindow import Ui_Login
        self.login = QtWidgets.QMainWindow()
        self.ui = Ui_Login()
        self.ui.setupUi(self.login)
        self.login.close()

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def ShowTransactions(self):
        from ATM_TransactionHistoryWindow import Ui_Transactions
        self.transactions = QtWidgets.QMainWindow()
        self.ui = Ui_Transactions()
        self.ui.setupUi(self.transactions)
        
        DATABASE = mysql.connector.connect(host='localhost', user='root',password='root',database='ATM_DB')
        CURSOR = DATABASE.cursor()
        CURSOR.execute(f'SELECT * FROM account_transactions WHERE CARD = "{self.label_ID.text()}"')
        TRANSACTIONS = CURSOR.fetchall()

        ROW_COUNT = 0
        COLUMN_COUNT = 1
        TRANSACTION_COUNT = 0

        for TRANSACTION in TRANSACTIONS:
            TRANSACTION_COUNT+=1
        if TRANSACTION_COUNT > 0:
            self.ui.btn_DeleteAllTransactions.setEnabled(True)
            self.ui.tableWidget.setRowCount(TRANSACTION_COUNT+1)
            self.ui.tableWidget.setColumnCount(3)

            self.ui.tableWidget.setItem(0,0,QtWidgets.QTableWidgetItem('Transaction Type'))
            self.ui.tableWidget.setItem(0,1,QtWidgets.QTableWidgetItem('Amount'))
            self.ui.tableWidget.setItem(0,2,QtWidgets.QTableWidgetItem('Date & Time'))
            self.ui.tableWidget.setColumnWidth(2,153)

            CURSOR.execute(f'SELECT * FROM account_transactions WHERE CARD = "{self.label_ID.text()}"')
            TRANSACTIONS = CURSOR.fetchall()
            for TRANSACTION in TRANSACTIONS:
                self.ui.tableWidget.setItem(COLUMN_COUNT,0,QtWidgets.QTableWidgetItem(str(TRANSACTION[2])))

                converted_number = '{:,}'.format(TRANSACTION[1])
                self.ui.tableWidget.setItem(COLUMN_COUNT,1,QtWidgets.QTableWidgetItem(f'₱{str(converted_number)}'))
                
                self.ui.tableWidget.setItem(COLUMN_COUNT,2,QtWidgets.QTableWidgetItem(str(TRANSACTION[3])))
                COLUMN_COUNT+=1
            self.transactions.show()
        else:
            self.transactions.show()
            from PyQt6.QtWidgets import QMessageBox
            self.bank = QMessageBox()
            self.bank.setWindowIcon(QtGui.QIcon('images/credit-card.png'))
            self.bank.setWindowTitle('HS ATM')
            self.bank.setIcon(QMessageBox.Icon.NoIcon)
            self.bank.setText('No record/s found.')
            self.bank.show()


    def ShowLogin(self):
        from ATM_LoginWindow import Ui_Login
        self.login = QtWidgets.QMainWindow()
        self.ui = Ui_Login()
        self.ui.setupUi(self.login)
        self.login.show()

    def ShowWithdrawWindow(self):
        from ATM_WithdrawWindow import Ui_Withdraw
        self.withdraw = QtWidgets.QMainWindow()
        self.ui = Ui_Withdraw()
        self.ui.setupUi(self.withdraw)
        self.ui.lineEdit_CardID.setText(self.label_ID.text())
        self.withdraw.show()
    
    def ShowDepositWindow(self):
        from ATM_DepositWindow import Ui_Deposit
        self.deposit = QtWidgets.QMainWindow()
        self.ui = Ui_Deposit()
        self.ui.setupUi(self.deposit)
        self.ui.lineEdit_CardID.setText(self.label_ID.text())
        self.deposit.show()

    def ShowAccountSettings(self):
        from ATM_AccountSettingsWindow import Ui_AccountSettings
        self.settings = QtWidgets.QMainWindow()
        self.ui = Ui_AccountSettings()
        self.ui.setupUi(self.settings)
        DATABASE = mysql.connector.connect(host='localhost',user='root',passwd='root',database='ATM_DB')
        CURSOR = DATABASE.cursor()
        CURSOR.execute(f'SELECT * FROM account_information where Name = "{self.label_User.text()}"')
        ACCOUNT = CURSOR.fetchall()
        for INFO in ACCOUNT:
            self.ui.lineEdit_CardID.setText(str(INFO[0]))
            self.ui.lineEdit_Pin.setText(str(INFO[1]))
            self.ui.lineEdit_Name.setText(str(INFO[2]))
            self.ui.lineEdit_Email.setText(str(INFO[3]))
            self.ui.lineEdit_Contact.setText(str(INFO[4]))
            self.ui.textEdit_Address.setPlainText(str(INFO[5]))
        self.settings.show()

    def AboutTheBank(self):
        from PyQt6.QtWidgets import QMessageBox
        self.bank = QMessageBox()
        self.bank.setWindowIcon(QtGui.QIcon('images/credit-card.png'))
        self.bank.setWindowTitle('HS ATM')
        self.bank.setIcon(QMessageBox.Icon.NoIcon)
        self.bank.setText('Welcome to HS bank of the Philippines.')
        self.bank.setInformativeText("As the first bank in Southeast Asia, we have established a history of client trust, financial strength and innovation. This is the very essence of HS bank, because people’s dreams matter to us. Our motivation is to help people get to where they want to be – whether that’s our colleagues, our clients or in the communities we are part of. HS bank has a clearly stated purpose - our WHY - which makes HS bank unique. It puts into words why HS exists and is our global organization’s fundamental reason for being, what defines us. As HS bank continues to grow in reach, headcount and revenue, our WHY shapes how we work with our clients, support our colleagues and help our communities succeed. It helps us make better decisions for ourselves and for all our stake¬holders, individually and as a global organization.")
        self.bank.show()

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "HS ATM Dashboard"))
        self.btn_Minimize.setText(_translate("Dashboard", "-"))
        self.btn_Exit.setText(_translate("Dashboard", "x"))
        self.label.setText(_translate("Dashboard", "HS ATM"))
        self.label_2.setText(_translate("Dashboard", "Welcome,"))
        self.label_5.setText(_translate("Dashboard", "Balance:"))
        self.label_6.setText(_translate("Dashboard", "₱"))
        self.btn_GetCash.setText(_translate("Dashboard", "Get Cash"))
        self.btn_Deposit.setText(_translate("Dashboard", "Deposit"))
        self.btn_AccountSettings.setText(_translate("Dashboard", "Account Settings"))
        self.btn_TransactionHistory.setText(_translate("Dashboard", "Transaction History"))
        self.btn_About.setText(_translate("Dashboard", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard = QtWidgets.QMainWindow()
    ui = Ui_Dashboard()
    ui.setupUi(Dashboard)
    Dashboard.show()
    sys.exit(app.exec())
